name: mariposario_ra
description: App Mariposario con Realidad Aumentada
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  mobile_scanner: ^4.0.0
  cupertino_icons: ^1.0.2
  ar_flutter_plugin: ^0.7.3
  vibration: ^1.8.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/sounds/
